SELECT
	*
FROM
	USERS;

SELECT
	NAME,
 -- 	SUBSTRING( name, 0, 5 ),
 -- 	POSITION( ' ' in name ),
	SUBSTRING(NAME, 0, POSITION(' ' IN NAME))  AS FIRST_NAME,
	SUBSTRING(NAME, POSITION(' ' IN NAME) + 1) AS LAST_NAME
 -- 	TRIM(SUBSTRING( name, POSITION( ' ' in name ) )) as trimmed_last_name
FROM
	USERS;

UPDATE USERS
SET
	FIRST_NAME = SUBSTRING(
		NAME,
		0,
		POSITION(' ' IN NAME)
	),
	LAST_NAME = SUBSTRING(
		NAME,
		POSITION(' ' IN NAME) + 1
	);

SELECT
	*
FROM
	USERS;